// <auto-generated />
using System;
using KYC.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace KYC.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KycDbContext))]
    [Migration("20260529205723_BdpComplianceAndGtm")]
    partial class BdpComplianceAndGtm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KYC.Domain.Entities.AmlComplianceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiModelsUsed")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("AssetFreezeNotifications")
                        .HasColumnType("integer");

                    b.Property<string>("BdpReferenceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CasesCriticalRisk")
                        .HasColumnType("integer");

                    b.Property<int>("CasesEnhancedDd")
                        .HasColumnType("integer");

                    b.Property<int>("CasesHighRisk")
                        .HasColumnType("integer");

                    b.Property<int>("CasesLowRisk")
                        .HasColumnType("integer");

                    b.Property<int>("CasesMediumRisk")
                        .HasColumnType("integer");

                    b.Property<int>("CasesSimplifiedDd")
                        .HasColumnType("integer");

                    b.Property<int>("CasesStandardDd")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PepMatches")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodicReviewsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodicReviewsOverdue")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ReportingYear")
                        .HasColumnType("integer");

                    b.Property<int>("SanctionMatches")
                        .HasColumnType("integer");

                    b.Property<int>("SarsSubmitted")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAmlAnalysts")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCasesApproved")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCasesProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCasesRejected")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCasesUnderReview")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRiskSignalsDetected")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("aml_compliance_reports", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Details")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("LlmPromptHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KycCaseId", "Timestamp");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.CaseDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CasePartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("DocumentKind")
                        .HasColumnType("integer");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("ExtractionModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExtractionPromptHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("IngestionStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawExtractionJson")
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageRelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("KycCaseId");

                    b.HasIndex("KycCaseId", "IngestionStatus");

                    b.ToTable("case_documents", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.CaseParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataCollectionBasis")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsOffshore")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPep")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSanctioned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Nif")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OffshoreJurisdiction")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("OwnershipPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<Guid?>("ParentPartyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RcbeDiscrepancyDetected")
                        .HasColumnType("boolean");

                    b.Property<bool>("RcbeDiscrepancyReported")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RcbeDiscrepancyReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RcbeVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UboDepthLevel")
                        .HasColumnType("integer");

                    b.Property<int>("VerificationMethod")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KycCaseId", "Nif");

                    b.ToTable("case_parties", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.CustomerAcceptancePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("BlockOffshoreAboveThreshold")
                        .HasColumnType("boolean");

                    b.Property<bool>("BlockShellCompanies")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EnhancedDdThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("HighRiskJurisdictionsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("OccasionalThreshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OffshoreBlockThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("ProhibitedCaeActivitiesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ProhibitedJurisdictionsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ReviewDaysCriticalRisk")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewDaysHighRisk")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewDaysLowRisk")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewDaysMediumRisk")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("customer_acceptance_policies", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.DocumentExtractedFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseDocumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FactKey")
                        .HasColumnType("integer");

                    b.Property<string>("FactValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseDocumentId");

                    b.HasIndex("KycCaseId", "FactKey");

                    b.ToTable("document_extracted_facts", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.DocumentExtractedParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Nif")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("OwnershipPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseDocumentId");

                    b.HasIndex("KycCaseId");

                    b.ToTable("document_extracted_parties", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.DpiaRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DocumentStoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MitigationMeasuresJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("NextReviewDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingActivitiesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("dpia_records", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.KycCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedByAnalystId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("AssetFreezeNotified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AssetFreezeNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedAnalystId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DueDiligenceJustification")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("DueDiligenceLevel")
                        .HasColumnType("integer");

                    b.Property<string>("FundsOriginDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("FundsOriginDocumentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("FundsOriginVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalBasisRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("NextReviewDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("RequestedCreditAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("RequestedCreditCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("SarReferenceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SarStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SarSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScoringEngineVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ScoringModelSnapshot")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("SecondApproverId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("kyc_cases", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.KycReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NarrativeHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NarrativeMarkdown");

                    b.HasKey("Id");

                    b.HasIndex("KycCaseId")
                        .IsUnique();

                    b.ToTable("kyc_reports", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.RiskSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalystNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("CasePartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CasePartyId");

                    b.HasIndex("KycCaseId");

                    b.ToTable("risk_signals", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.ScoringEngineConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CloudModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LocalModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPromptHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("WeightsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.ToTable("scoring_engine_configs", (string)null);
                });

            modelBuilder.Entity("KYC.Infrastructure.Persistence.Entities.KycCaseScanProgressRow", b =>
                {
                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedScans")
                        .HasColumnType("integer");

                    b.Property<int>("FailedScans")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScans")
                        .HasColumnType("integer");

                    b.HasKey("KycCaseId");

                    b.ToTable("kyc_case_scan_progress", (string)null);
                });

            modelBuilder.Entity("KYC.Infrastructure.Persistence.Entities.ReportEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentChunk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<HalfVector>("Embedding")
                        .IsRequired()
                        .HasColumnType("halfvec(2048)");

                    b.Property<Guid>("KycCaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KycCaseId");

                    b.ToTable("report_embeddings", (string)null);
                });

            modelBuilder.Entity("KYC.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("KYC.Domain.Entities.KycCase", null)
                        .WithMany("AuditTrail")
                        .HasForeignKey("KycCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KYC.Domain.Entities.CaseDocument", b =>
                {
                    b.HasOne("KYC.Domain.Entities.KycCase", null)
                        .WithMany("Documents")
                        .HasForeignKey("KycCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KYC.Domain.Entities.CaseParty", b =>
                {
                    b.HasOne("KYC.Domain.Entities.KycCase", null)
                        .WithMany("Parties")
                        .HasForeignKey("KycCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KYC.Domain.ValueObjects.RiskScore", "PartyScore", b1 =>
                        {
                            b1.Property<Guid>("CasePartyId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("AdverseMediaScore")
                                .HasColumnType("integer")
                                .HasColumnName("party_score_adverse_media");

                            b1.Property<int?>("FinancialScore")
                                .HasColumnType("integer")
                                .HasColumnName("party_score_financial");

                            b1.Property<int?>("JudicialScore")
                                .HasColumnType("integer")
                                .HasColumnName("party_score_judicial");

                            b1.Property<string>("Justification")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)")
                                .HasColumnName("party_score_justification");

                            b1.Property<int>("Overall")
                                .HasColumnType("integer")
                                .HasColumnName("party_score_overall");

                            b1.Property<int?>("PepScore")
                                .HasColumnType("integer")
                                .HasColumnName("party_score_pep");

                            b1.Property<int?>("SanctionsScore")
                                .HasColumnType("integer")
                                .HasColumnName("party_score_sanctions");

                            b1.Property<int?>("UboStructureScore")
                                .HasColumnType("integer")
                                .HasColumnName("party_score_ubo");

                            b1.HasKey("CasePartyId");

                            b1.ToTable("case_parties");

                            b1.WithOwner()
                                .HasForeignKey("CasePartyId");
                        });

                    b.Navigation("PartyScore");
                });

            modelBuilder.Entity("KYC.Domain.Entities.DocumentExtractedFact", b =>
                {
                    b.HasOne("KYC.Domain.Entities.CaseDocument", null)
                        .WithMany("ExtractedFacts")
                        .HasForeignKey("CaseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KYC.Domain.Entities.DocumentExtractedParty", b =>
                {
                    b.HasOne("KYC.Domain.Entities.CaseDocument", null)
                        .WithMany("ExtractedParties")
                        .HasForeignKey("CaseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KYC.Domain.Entities.KycCase", b =>
                {
                    b.OwnsOne("KYC.Domain.ValueObjects.RiskScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("KycCaseId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("AdverseMediaScore")
                                .HasColumnType("integer")
                                .HasColumnName("score_adverse_media");

                            b1.Property<int?>("FinancialScore")
                                .HasColumnType("integer")
                                .HasColumnName("score_financial");

                            b1.Property<int?>("JudicialScore")
                                .HasColumnType("integer")
                                .HasColumnName("score_judicial");

                            b1.Property<string>("Justification")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)")
                                .HasColumnName("score_justification");

                            b1.Property<int>("Overall")
                                .HasColumnType("integer")
                                .HasColumnName("score_overall");

                            b1.Property<int?>("PepScore")
                                .HasColumnType("integer")
                                .HasColumnName("score_pep");

                            b1.Property<int?>("SanctionsScore")
                                .HasColumnType("integer")
                                .HasColumnName("score_sanctions");

                            b1.Property<int?>("UboStructureScore")
                                .HasColumnType("integer")
                                .HasColumnName("score_ubo");

                            b1.HasKey("KycCaseId");

                            b1.ToTable("kyc_cases");

                            b1.WithOwner()
                                .HasForeignKey("KycCaseId");
                        });

                    b.Navigation("Score");
                });

            modelBuilder.Entity("KYC.Domain.Entities.KycReport", b =>
                {
                    b.HasOne("KYC.Domain.Entities.KycCase", null)
                        .WithOne("FinalReport")
                        .HasForeignKey("KYC.Domain.Entities.KycReport", "KycCaseId");
                });

            modelBuilder.Entity("KYC.Domain.Entities.RiskSignal", b =>
                {
                    b.HasOne("KYC.Domain.Entities.KycCase", null)
                        .WithMany("RiskSignals")
                        .HasForeignKey("KycCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KYC.Domain.Entities.CaseDocument", b =>
                {
                    b.Navigation("ExtractedFacts");

                    b.Navigation("ExtractedParties");
                });

            modelBuilder.Entity("KYC.Domain.Entities.KycCase", b =>
                {
                    b.Navigation("AuditTrail");

                    b.Navigation("Documents");

                    b.Navigation("FinalReport");

                    b.Navigation("Parties");

                    b.Navigation("RiskSignals");
                });
#pragma warning restore 612, 618
        }
    }
}
