FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY KYC.sln ./
COPY src ./src
RUN dotnet restore src/KYC.Workers/KYC.Workers.csproj
RUN dotnet publish src/KYC.Workers/KYC.Workers.csproj -c Release -o /app/publish --no-restore

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "KYC.Workers.dll"]
